[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "running-analyzer"
version = "0.1.0"
description = "A Python package to analyze running data"
authors = [{name = "Zach Merrill", email = ""}]
license = {text = "MIT"}
dependencies = []
